### PR TITLE
Accommodating GIF format images

### PR DESCRIPTION
**Pull request by JasmoMyer**

### CODE REVIEW

**Comment by jansher** [comment]
👍

**Comment by baob** [comment]
Doesn't appear that there are any guarantees that the resultant image conversion will happen ... have you checked that ?  (Guessing you have but it's nice to be sure).

**Comment by JasmoMyer** [comment]
Good point. Yes - I've checked that locally - but not formalised the check.

**Comment by baob** [comment]
Is that easy to do, do you think ? I'd say, since we're talking about supporting a whole new format, it might be wise to get a smoke test in there, at least.

**Comment by baob** [comment]
When it passes in CI, 👍

**Pull request merged**
